/// Flutter icons LaundryIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LaundryIcons
///      fonts:
///       - asset: fonts/LaundryIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class LaundryIcons {
  LaundryIcons._();

  static const _kFontFam = 'LaundryIcons';
  static const String? _kFontPkg = null;

  static const IconData alteration = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag3 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beach2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bikini = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beanie2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beanie1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blouse1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blouse2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blouse3 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blouse4 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom1 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom2 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom3 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowtie = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxers1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxers2 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxers3 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxers4 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefs1 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefs2 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefs3 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camisole1 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camisole2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camisole3 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camisole4 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocktail_dress = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocktail_dress2 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dress_shirt = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gloves = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hat2 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hat3 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iron = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laundry = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_skirt = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_skirt2 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mini_skirt = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poloshirt_vneck = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poloshirt = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robe = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sock1 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sock2 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sock3 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steam = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tie = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt_vneck = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tie2 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vest1 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vest2 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vest3 = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wearable = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
