// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5cFWpknVs_M2phRWoPCYLzmA3a_dTEPw',
    appId: '1:157769265704:web:9d43422223f0acc091fb1d',
    messagingSenderId: '157769265704',
    projectId: 'laundry-pos-app-8bdaa',
    authDomain: 'laundry-pos-app-8bdaa.firebaseapp.com',
    storageBucket: 'laundry-pos-app-8bdaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQPcVjGN1NSBSqsXTo2a09MURWPY0RoQU',
    appId: '1:157769265704:android:22534f99ca3fec0b91fb1d',
    messagingSenderId: '157769265704',
    projectId: 'laundry-pos-app-8bdaa',
    storageBucket: 'laundry-pos-app-8bdaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvYihAz0OAo0nQvA71SmK1HsjohaOUdBg',
    appId: '1:157769265704:ios:b9f54da703aa2ce691fb1d',
    messagingSenderId: '157769265704',
    projectId: 'laundry-pos-app-8bdaa',
    storageBucket: 'laundry-pos-app-8bdaa.appspot.com',
    iosClientId: '157769265704-nvkmjq487kbvedh9gt4mq17187gm1edp.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryApp',
  );
}
